/**
 * Controller for the JavaFX application that visualizes Dangerous Dog Orders
 * issued by the City of Toronto.
 *
 * <p>This class is responsible for:
 * <ul>
 *   <li>Loading and parsing CSV data from the Toronto Open Data Portal</li>
 *   <li>Storing records as {@code DangerousDogRecord} objects</li>
 *   <li>Performing algorithmic analysis such as counting totals per year</li>
 *   <li>Dynamically updating a {@link BarChart} based on user selection</li>
 *   <li>Managing navigation between a home page view and data visualizations</li>
 * </ul>
 *
 * <p>The GUI supports live filtering using a {@link ComboBox}, allowing users
 * to explore trends by order severity category. Chart updates occur immediately
 * upon user interaction.
 */

import javafx.fxml.FXML;
import javafx.geometry.Pos;
import javafx.scene.Node;
import javafx.scene.chart.BarChart;
import javafx.scene.chart.CategoryAxis;
import javafx.scene.chart.NumberAxis;
import javafx.scene.chart.XYChart;
import javafx.scene.control.ComboBox;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.StackPane;
import javafx.scene.layout.VBox;
import javafx.scene.text.Font;
import javafx.scene.text.Text;

import java.io.File;
import java.util.*;

public class Controller {
    @FXML
    BorderPane borderPane;
    BarChart<String, Number> barChart;
    XYChart.Series<String, Number> series;
    ComboBox<String> orderTypeBox; // @ai generated this line and introduced me to the concept of ComboBox when researching additional JavaFx components
    List<DangerousDogRecord> records = new ArrayList<>();
    Text instructionText;
    Text statsText;
    StackPane homePane;
    VBox chartPane;

    /**
     * Initializes the JavaFX user interface after the FXML layout has been loaded.
     *
     * <p>This method:
     * <ul>
     *   <li>Sets up the chart, axes, dropdown menu, and home page view</li>
     *   <li>Loads and processes CSV data into memory</li>
     *   <li>Displays the initial view based on the default dropdown selection</li>
     * </ul>
     *
     * @throws Exception if the CSV resource cannot be located or read
     */
    public void initialize() throws Exception{
        setUp();
        processData();
        updateView();
    }

    /**
     * Constructs and styles all static GUI components used in the application.
     *
     * <p>This includes:
     * <ul>
     *   <li>Creating and configuring the bar chart and axes</li>
     *   <li>Initializing the data series for chart visualization</li>
     *   <li>Setting up the dropdown menu used for filtering</li>
     *   <li>Creating the home page instruction view</li>
     *   <li>Applying fonts, colors, and layout styling</li>
     * </ul>
     *
     * <p>The dropdown menu setup and event handling logic were initially generated
     * with AI assistance. {@ai}
     */
    public void setUp(){
        CategoryAxis xAxis = new CategoryAxis();
        xAxis.setLabel("Year");
        xAxis.setAutoRanging(false);

        NumberAxis yAxis = new NumberAxis();
        yAxis.setLabel("Number of Orders");
        yAxis.setAutoRanging(false);

        barChart = new BarChart<>(xAxis, yAxis);
        barChart.setTitle("Dangerous Dog Orders Issued in Toronto");

        series = new XYChart.Series<>();
        series.setName("Number of Orders");

        barChart.getData().add(series);

        // The next 5 lines of code were generated by @ai
        orderTypeBox = new ComboBox<>();
        orderTypeBox.getItems().add("Home page");
        orderTypeBox.getItems().add("Total");
        orderTypeBox.setValue("Home page");
        orderTypeBox.setOnAction(e -> updateView());

        borderPane.setTop(orderTypeBox);

        instructionText = new Text("This GUI analyzes Dangerous Dog Orders issued by the City of Toronto.\n"
                + "\n" +  "Click the dropdown menu at the top-left corner to explore how the number of orders varies by year based on the severity of the order.\n"
                + "\n" + "Selecting a specific category will update the bar chart accordingly.\n"
                + "\n" + "The chart will display the total number of a certain order issued per year along with the yearly average, minimum, and maximum.\n"
                + "\n" + "Bar colors indicate relative safety in a certain year.\n"
                + "\n" + "A blue bar indicates that the specific year was relatively safe (less than or equal to 25 orders).\n"
                + "\n" + "A red bar indicates that the specific year was relatively unsafe (more than 25 orders).\n" +
                "\n" + "I used 25 orders as a threshold for safety since there are 25 wards in Toronto.");
        instructionText.setFont(Font.font("Georgia", 20));

        statsText = new Text();
        statsText.setFont(Font.font("Georgia", 16));

        chartPane = new VBox(10, barChart, statsText);
        chartPane.setAlignment(Pos.CENTER);

        borderPane.setStyle("-fx-background-color: #e0f7fa;");
        homePane = new StackPane(instructionText);
        borderPane.setCenter(chartPane);
        barChart.setStyle("-fx-background-color: e0f7fa;");

        Node plotBackground = barChart.lookup(".chart-plot-background");
        if(plotBackground != null){
            plotBackground.setStyle("-fx-background-color: #e0f7fa;"); // Light blue hex
        }
        xAxis.setStyle("-fx-font-family: 'Georgia'; -fx-font-size: 15px;");
        yAxis.setStyle("-fx-font-family: 'Georgia'; -fx-font-size: 15px;");
        orderTypeBox.setStyle("-fx-font-family: 'Georgia';" + "-fx-font-size: 15px;");
        xAxis.setTickLabelFont(javafx.scene.text.Font.font("Georgia", 15));
        yAxis.setTickLabelFont(javafx.scene.text.Font.font("Georgia", 15));
        Node title = barChart.lookup(".chart-title");
        if (title != null) {
            title.setStyle("-fx-font-family: 'Georgia'; -fx-font-size: 25px;");
        }
        barChart.setLegendVisible(false);
    }

    /**
     * Reads and processes Dangerous Dog Order data from a CSV file bundled with the application.
     *
     * <p>This method:
     * <ul>
     *   <li>Skips the CSV header row</li>
     *   <li>Extracts the order type and year from each record</li>
     *   <li>Creates {@link DangerousDogRecord} objects for each entry</li>
     *   <li>Dynamically populates dropdown filter options based on unique order types</li>
     * </ul>
     *
     * @throws Exception if the CSV file cannot be found or read
     */
    public void processData() throws Exception{
        File file = new File(Main.class.getClassLoader().getResource("dangerous_dogs.csv").toURI());
        Scanner sc = new Scanner(file);
        boolean firstLine = true;
        while(sc.hasNextLine()){
            String line = sc.nextLine();
            // The below if statement skips the header row
            if(firstLine){
                firstLine = false;
                continue;
            }
            Scanner lineScanner = new Scanner(line);
            lineScanner.useDelimiter(",");
            for (int i = 0; i < 7; i++) lineScanner.next(); // skip 7 columns
            String orderType = lineScanner.next(); // reads the order type
            lineScanner.next();

            String date = lineScanner.next(); // reads the date
            String yearStr = date.substring(0, 4); // extracts year from the date that is in the format yyyy-mm-dd
            records.add(new DangerousDogRecord(yearStr, orderType));
            if(!orderTypeBox.getItems().contains(orderType)){
                orderTypeBox.getItems().add(orderType);
            }
        }
        sc.close();
    }

    /**
     * Updates the bar chart to reflect the currently selected order type.
     *
     * <p>This method:
     * <ul>
     *   <li>Filters records based on the dropdown selection</li>
     *   <li>Counts the total number of orders per year</li>
     *   <li>Sorts years chronologically</li>
     *   <li>Rebuilds the chart data</li>
     *   <li>Applies conditional color styling based on order thresholds</li>
     *   <li>Computes and displays summary statistics including average, minimum,
     *     and maximum yearly orders</li>
     * </ul>
     *
     * <p>If the "Home page" option is selected, the method exits early without
     * modifying the chart.
     *
     * <p>This dynamic filtering and chart update logic was originally generated
     * with AI assistance and later modified. {@ai}
     */
    public void updateChart(){
        String selectedType = orderTypeBox.getValue(); // This line was generated by @ai
        if(orderTypeBox.getValue().equals("Home page")) {
            return;
        }
        series.getData().clear();
        Map<String, Integer> counts = new HashMap<>();

        for (DangerousDogRecord record : records) {
            if (!selectedType.equals("Total") &&
                    !record.getOrderType().equals(selectedType)) {
                continue;
            }

            //The below line was generated by @ai
            counts.put(record.getYear(), counts.getOrDefault(record.getYear(), 0) + 1);
        }

        List<String> sortedYearsStr = new ArrayList<>(counts.keySet());
        List<Integer> sortedYears = new ArrayList<>();
        for(String yearStr: sortedYearsStr){
            int year = Integer.parseInt(yearStr);
            sortedYears.add(year);
        }
        Collections.sort(sortedYears);

       // The below 2 lines were generated by @ai
        CategoryAxis xAxis = (CategoryAxis) barChart.getXAxis();
        xAxis.getCategories().clear();

        for(int year: sortedYears){
            String yearStr = Integer.toString(year);
            xAxis.getCategories().add(yearStr);
        }
        series = new XYChart.Series<>();
        series.setName("Number of Orders");
        for (Integer year: sortedYears) {
            series.getData().add(new XYChart.Data<>(year.toString(), counts.get(year.toString())));
        }
        barChart.getData().clear();
        barChart.getData().add(series);

        series.getData().forEach(data -> {
            Node node = data.getNode();
            if (data.getYValue().doubleValue() > 25) {
                node.setStyle("-fx-bar-fill: red;");
            } else {
                node.setStyle("-fx-bar-fill: blue;");
            }
        });

        int total = 0;
        int min = Integer.MAX_VALUE;
        int max = Integer.MIN_VALUE;
        String minYear = "";
        String maxYear = "";
        for(Map.Entry<String, Integer> orderType : counts.entrySet()){
            total += orderType.getValue();
            if(min > orderType.getValue()){
                min = orderType.getValue();
                minYear = orderType.getKey();
            }
            if(max < orderType.getValue()){
                max = orderType.getValue();
                maxYear = orderType.getKey();
            }
        }
        int average = (int)Math.round(total / (double)counts.size());

        if(selectedType.equals("Total")){
            statsText.setText("Average " + selectedType.toLowerCase() + " orders per year (rounded to a whole number): " + average
                    + "\nMinimum " + selectedType.toLowerCase() + " orders in a year: " + min + " (" + minYear + ")"
                    + "\nMaximum " + selectedType.toLowerCase() + " orders in a year: " + max + " (" + maxYear + ")"
            );
        }
        else{
            statsText.setText("Average \"" + selectedType.toLowerCase() + "\" orders per year (rounded to a whole number): " + average
                    + "\nMinimum \"" + selectedType.toLowerCase() + "\" orders in a year: " + min + " (" + minYear + ")"
                    + "\nMaximum \"" + selectedType.toLowerCase() + "\" orders in a year: " + max + " (" + maxYear + ")"
            );
        }
    }

    /**
     * Switches the center content of the application between the home page
     * and the bar chart visualization.
     *
     * <p>If the user selects "Home page", an instruction panel is displayed.
     * Otherwise, the bar chart is shown and updated to match the selected
     * order category.
     *
     * <p>This method enables simple navigation within the application using
     * a single dropdown menu.
     */
    public void updateView(){
        String selectedType = orderTypeBox.getValue();
        if (selectedType.equals("Home page")){
            borderPane.setCenter(homePane);
        }
        else{
            borderPane.setCenter(chartPane);
            updateChart();
        }
    }
}